# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=15)),
                ('trans', models.CharField(max_length=15)),
            ],
        ),
    ]
