# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiszki', '0002_words_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='counter',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
